### ISSUE TITLE
Chip-select is "slow"

### ISSUE THREAD

**Issue by AndreKlang** [RobTillaart/AD9833#19]
Hi!
Want to start with a quick thanks, so far the library has worked really well.

But :)

I was having some really wierd issues where one of my two modules would just do "what ever", and one would work most of the time, then just freak out. I have finally found out that the default SPI frequency is too high for my cheap esp32's.

I hooked it up to my scope (first time trying that for logic analyzing), and I couldn't really make sense of it. The signals were anything but square wave, more like extreme noise (and couldn't really be decoded). So I made an isolated test to look more on the pure SPI-signal, completely isolated from this library.

An unexpected thing I found is that if the chip-select is set *within* the transaction, it is MUCH faster.

I.e, this;
```cpp
  digitalWrite(PIN_AD_A_SELECT, LOW);
  waveSpi->beginTransaction(spi_settings);
  waveSpi->write(++count);
  waveSpi->endTransaction();
  digitalWrite(PIN_AD_A_SELECT, HIGH);
```
produces this:
![cs-around-transaction](https://github.com/user-attachments/assets/9d0b1621-a62a-4cbf-837a-662ec6ac56d2)

And this:

```cpp
  waveSpi->beginTransaction(spi_settings);
  digitalWrite(PIN_AD_A_SELECT, LOW);
  waveSpi->write(++count);
  digitalWrite(PIN_AD_A_SELECT, HIGH);
  waveSpi->endTransaction();
```
produces this:
![cs-in-transaction](https://github.com/user-attachments/assets/62935ba9-d9ac-4f8e-bfc3-6a97c9162761)

(The purple line is the chip-select)

Thought I'd share my findings, I have no idea why this is, or if this translates to faster code executions.

Anyway, setting the frequency to `SPI_CLOCK_DIV8` will make it reliable (on my boards), anything faster than that will have random faults. So thanks for `setSPIspeed()` :)

**Comment by RobTillaart** [comment]
Thanks for reporting your experiences.

My interpretation of your screenshots is that **waveSpi->beginTransaction(spi_settings);** and **waveSpi->endTransaction();** take quite some time 14 us  as the actual data transfer only takes about 1 us.

For the MCU it does not make a difference, the number of (mandatory) operations is the same.

It might be that the 9833 react faster when the **chip-select** is within the transaction. 
Could save 5-6 us or so,

**Comment by RobTillaart** [comment]
> Want to start with a quick thanks, so far the library has worked really well.

Good to hear, you're welcome!

**Comment by RobTillaart** [comment]
@AndreKlang 
Are there any other issues with the AD9833 you want to discuss?

**Comment by AndreKlang** [comment]
Had some more time yesterday evening to play around..

It might well be that the begin/endTransaction is what is taking the additional time, I'll experiment with adding an additional flip-flop channel around the whole thing..

Anyways, reducing the speed did help with the actual AD9833's, both of my boards are now completely reliable on all features.

I did notice an annoying thing though, that I haven't had the time to dig into yet. If I set one board to 1000hz, and the other to 2000hz, there's a drift between them. (both boards run off the same crystal) If I instead set the second board to 1999.9hz, they sync back up.
I assume this has to do with the float into `setFrequency`. But this is a different subject, I'll play around and see what I come up with..

**Comment by RobTillaart** [comment]
> If I set one board to 1000hz, and the other to 2000hz, there's a drift between them. (both boards run off the same crystal) If I instead set the second board to 1999.9hz, they sync back up.
I assume this has to do with the float into setFrequency. 

Mmm,   Floats (IEEE754) should be able to exactly represent 1000 and 2000 with its 23 bit mantissa.

I look into it.

**Comment by RobTillaart** [comment]
Confirmed.

### setFrequency

When setting f = 1000.0 the internal register value is 10737
When setting f = 2000.0 the internal register value is 21475
When setting f = 1999.9 the internal register value is 21474  

When changing this line in **setFrequency()**  (you can verify this yourself, line 174 - AD9833.cpp)
```cpp
uint32_t freq = round(newFrequency * _crystalFreqFactor);
==>
uint32_t freq = uint32_t(newFrequency * _crystalFreqFactor);
```

The numbers are 

1000.0 -> 10737
2000.0 -> 21474
1999.9 -> 21473

So the rounding which gives a more accurate frequency is the cause for the drift. 


### setPhase

This rounding is also applied in the **setPhase()** function so phases is probably drifting too.
As I have no setup, can you confirm this?


### proposal

My proposal is to make two functions
- **void setUseRounding(bool flag = true)** set an internal flag which default = true.
- **bool getUseRouding()** to fetch current setting.

You set the flag once in setup() and the user would be OK for the rest of the program.
It would affect both the phase and frequency.
This would not break the existing interface.

Alternative would be an extra parameter for **setFrequency()** and **setPhase()** which must be given at every call.
That would be explicit and more work.

Opinion?

**Comment by RobTillaart** [comment]
Labeled as bug to give it some priority.

**Comment by RobTillaart** [comment]
Created a develop branch + PR for the proposed solution.

**Comment by RobTillaart** [comment]
@AndreKlang 

If you have time can you confirm the develop branch fixes the drift?
when using **AD.setUseRounding(false)**

**Comment by AndreKlang** [comment]
Well, I can absolutely say that it works! Disabling rounding (using your dev-branch) did the trick, zero drift.

Have to say that you're the most active and responsive maintainer I've come across, good work and huge thanks!

The next thing I'll look into is the phase, I don't think it has anything to do with the library, more with how the chip works. The phase seam to be relative to the time of the set frequency. I.e. changing the frequency yield a random phase between the two boards. Changing the waveform does not change the phase though.. But oddly `setWave(AD9833_OFF)` (and back) does change it..

https://github.com/user-attachments/assets/13eeb4c3-3455-4f16-96e5-35b3d4c5271a

I'm sort of hoping that I can enable both chip-selects, then cycle the wave to OFF and back on both of them at the same time, possibly syncing them. Haven't looked into how the packets look though if that is even possible.

**Comment by RobTillaart** [comment]
You're welcome. I try to keep up with issues however some take longer and some are relative easy to fix.

To sync multiple devices I think you should use the FSYNC line (yes extra hardware).

Set fsync low on all devices, set the frequency for them, and set the fsync high again.
If you connect all fsyncs to one pin, or to multiple pins that can be set in one call (e.g. an io register) .

Last idea is just set the frequency after another and adjust the phase to compensate for the time between the two setFreq() calls.

Does this help?

**Comment by RobTillaart** [comment]
Nice video of the signals without drift.

**Comment by RobTillaart** [comment]
As the fix works I'm going to merge the develop branch into the master branch.
For new issues better open a new issue to keep topics clear.

Thanks for testing, appreciated!
