### ISSUE TITLE
AD9833 Duty Cycle Control

### ISSUE THREAD

**Issue by XRAD-XRAY** [RobTillaart/AD9833#21]
Thank you for your fantastic libraries. Is there any way through code to adjust DUTY CYCLE on AD9833 square wave output?  Thank you

**Comment by RobTillaart** [comment]
Thanks for the question,

From my head I assume it is not supported by the device otherwise I expect it would be mentioned in the **future** section.
Will check the datasheet again later this weekend for a more definite answer.

**Comment by RobTillaart** [comment]
What frequency range and duty cycle range are you looking for?

**Comment by RobTillaart** [comment]
Checked the datasheet quickly but it does not mention duty cycle in any of its registers.

The only library I have that support duty cycle is 

https://github.com/RobTillaart/FunctionGenerator

which generates square waves in software. 
Option to use a 2nd processor as square wave  generator?

**Comment by RobTillaart** [comment]
A quick search only revealed this analog chip which can be controlled by potentiometers.
DADJ = Duty Cycle adjust
FADJ = Frequency adjust

https://www.analog.com/media/en/technical-documentation/data-sheets/MAX038.pdf

----

![image](https://github.com/user-attachments/assets/509e2379-f4ef-4c29-92b6-84c2cc6505ef)

**Comment by XRAD-XRAY** [comment]
Hello Rob,

Thank you for replying. I read all of your replies and links. I looked through the data for AD9833 and I did not see duty control either.  I have used several frequency generators such as AD9833, AD9850,  this from Amazon (SING F LTD 2PCS PWM Signal Generator PWM Square Wave Signal Generator LCD Display Signal Generator Module 1 Channel Frequency Generator Rectangular Wave Generator), and a few others. It is for a plasma experiment requiring 0-34kHz square wave.

I have beautiful arduino control of frequency with your AD9833 code, and I can control amplitude with variable resistor set-up.  To complete the experiment, I wanted to also control duty cycle. But I can update at later stage with another wave generator. I will send link to my build using your AD9833 lib at Adafruit when done.

Cheers, Fred



________________________________

**Comment by RobTillaart** [comment]
@XRAD-XRAY 

Got an idea but no time to test it in practice on short term.

Take 2x AD9833 and connect the outputs with an AND port.

Set both to the same frequency
Change the phase of one of them.
Then the overlapping part changes 
The output of the AND port will show a shorter pulse, roughly from 0..50%

To get an duty cycle above 50% to 100% you need to connect the 2x AD9833 to an OR port.

Works only with square waves.

Assumption is that the two devices have the exact same frequency. 

----

If you split the output if one AD9833 in two and you would delay one for a configurable time (interrupt driven extra processor?) it might work too.

So far some sunday morning thoughts...

**Comment by XRAD-XRAY** [comment]
Hi Rob,

 Great idea. However, I need the direct output voltage levels (Vpp) of the AD9833 breakout to operate a flyback transformer board (where I can currently control amplitude based on min and max V peaks) . It took me a while to tune this flyback so I don't really want to change hardware setup.  If I run dual AD9833 outputs through ports, i'm back to line level. My current setup is fairly simple.

 I did find a Fq generator board that allows Fq and duty cycle control,  but the Fq chip name has been ground off so I can't code serial control, and the voltage swing is 2/3rd's more positive than negative.

But it would be nice to test the different duty cycles for my flyback setup......

Cheers, Fred



________________________________

**Comment by RobTillaart** [comment]
> I did find a Fq generator board that allows Fq and duty cycle control, 

link?

**Comment by XRAD-XRAY** [comment]
Sure!! Thank you!!

________________________________

**Comment by XRAD-XRAY** [comment]
Hi Rob, sorry for slow reply. 
here is the link for Fq generator with duty and Fq control:Amazon.com:
DEVMO Signal Generator PWM Pulse Frequency Duty Cycle Adjustable
Module LCD Display Compatible with Ar-duino Raspberry Pi : Industrial
& Scientific [1]
Unfortunately, the chip name has been erased off the back of the chip
so I can't see which one it is. Also, looks like possible serial
control, but no data sheets or anything. Possible, just a
microprocessor which was preloaded with code, and not a specific Fq
chip like AD9833. However, I purchased one of these DEVMO signal
generators and tested it on scope. The square wave has a shark fin
architecture. It is also MORE positive than negative. The duty and Fq
control works just fine. 
For my flyback, I just need to control duty at about 10-50% and a
sharp square wave (which your code and AD9833 produce), BUT 

Links:
------
[1]
https://www.amazon.com/DEVMO-Generator-Frequency-Adjustable-Display/dp/B07S38SH4K/ref=sr_1_4?crid=1DC9VPWERLPTK&dib=eyJ2IjoiMSJ9.TP5iORQSWshlGPpieHfwnRd6ghzoUtlnM5q3Oxt8lQoxqAzqj0cJRyxCAL8Wor5P12d3xuTNn1wHuFexQj_XO9ui34IPAPrN31m2Fme7yI1ZojNmUrq22sMgaZCV4ijSOfU2O_W1jbFadgKuXc3MrVSVBah6M856iVXCfh3PmbIEUJhiN_Ch8i93xibkyoOouDI-pBoM9mnwDV2cheVkroPI2QLaZkmjlC6lnNWXn5o.CrBb_kA9MNBp33Cn12wQwUWFy8jfBZ_cj7pBNqR9ExA&dib_tag=se&keywords=frequency+generator+with+duty+control+arduino&qid=1731418342&sprefix=frequency+generator+with+duty+control+arduino%2Caps%2C72&sr=8-4
[2]
https://github.com/RobTillaart/AD9833/issues/21#issuecomment-2466740984
[3]

**Comment by RobTillaart** [comment]
The reviews confirms your notes

> For my flyback, I just need to control duty at about 10-50% and a
sharp square wave (which your code and AD9833 produce), BUT


Q: Do you consider a separate ESP32 as function generator?

Not tested, but I expect it should be able to generate both the frequency and the duty cycle

**Comment by XRAD-XRAY** [comment]
Ok, thx for checking. I based my build on Teensy 4.0 and MEGA2560. I
am sure that I can code for Fq and Duty on the Teensy. BUT, I really
like using the AD9833 breakout board and you GitHub lib.

	-----------------------------------------From: "Rob Tillaart" 
To: "RobTillaart/AD9833"
Cc: "XRAD-XRAY", "Mention"
Sent: Tuesday November 12 2024 9:31:02AM
Subject: Re: [RobTillaart/AD9833] AD9833 Duty Cycle Control (Issue
#21)

	The reviews confirms your notes  

	For my flyback, I just need to control duty at about 10-50% and a
 sharp square wave (which your code and AD9833 produce), BUT  

	Q: Do you consider a separate ESP32 as function generator? 

	Not tested, but I expect it should be able to generate both the
frequency and the duty cycle 

	—
 Reply to this email directly,  view it on GitHub [1], or  unsubscribe
[2].
 You are receiving this because you were mentioned.Message ID:  

Links:
------
[1]
https://github.com/RobTillaart/AD9833/issues/21#issuecomment-2470690965
[2]

**Comment by RobTillaart** [comment]
@XRAD-XRAY 

As the library cannot solve your duty cycle requirement, I propose to close the issue.
If you find a chip that can do duty cycle and frequency as needed and no library exists, let me know.

**Comment by XRAD-XRAY** [comment]
sounds good to me . thx for your help!!

	-----------------------------------------From: "Rob Tillaart" 
To: "RobTillaart/AD9833"
Cc: "XRAD-XRAY", "Mention"
Sent: Thursday November 14 2024 4:26:40AM
Subject: Re: [RobTillaart/AD9833] AD9833 Duty Cycle Control (Issue
#21)

	@XRAD-XRAY [1] 

	As the library cannot solve your duty cycle requirement, I propose to
close the issue.
 If you find a chip that can do duty cycle and frequency as needed and
no library exists, let me know. 

	—
 Reply to this email directly,  view it on GitHub [2], or  unsubscribe
[3].
 You are receiving this because you were mentioned.Message ID:  

Links:
------
[1] https://github.com/XRAD-XRAY
[2]
https://github.com/RobTillaart/AD9833/issues/21#issuecomment-2475827306
[3]

**Comment by RobTillaart** [comment]
(for reference purpose)

Found two analog kits for function generators based upon 

- https://www.analog.com/media/en/technical-documentation/data-sheets/MAX038.pdf
- https://www.sparkfun.com/datasheets/Kits/XR2206_104_020808.pdf

(google for kits itself)

Might be interesting to do for testing / experiment,

- https://www.youtube.com/watch?v=VurYqRFdnvc


- https://www.renesas.com/en/document/dst/icl8038-datasheet

**Comment by RobTillaart** [comment]
@XRAD-XRAY 

How about 

- https://microcontrollerslab.com/interface-ad9850-dds-signal-generator-module-with-arduino-pinout-features/

It has a duty cycle potentiometer which in theory could be replaced by a digital potentiometer.

Cannot see the Ohm range of the potentiometer and if it is linear or logarithmic

Library for frequency: https://github.com/RobTillaart/AD985X
Also have several digipot libraries.

**Comment by RobTillaart** [comment]
@XRAD-XRAY 

Of course !
one can add an opamp and digipot after the sine output of the AD9833. 
The opamp makes a square wave of the sine if the voltage is above a threshold. The digipot is used to set that threshold, resulting in duty cycle control.

Cheaper than buying the AD9850 which showed the trick in the schema above.

**Comment by RobTillaart** [comment]
From - https://oshwlab.com/DonWinesK5DW/ad9850-signal-generator-module

Seems to be a 10KOhm pot

![image](https://github.com/user-attachments/assets/367b1d6f-eaac-442f-a28a-d2350942db4b)

**Comment by RobTillaart** [comment]
@XRAD-XRAY 

Opamp trick

![image](https://github.com/user-attachments/assets/081ea2af-5983-46f9-8dcd-23feb42893fd)

**Comment by XRAD-XRAY** [comment]
funny, I zoomed this board image a few weeks ago. I do have a knob
sized pot for it. but the issue was the output wave is shark fin and
not square. something with the board design, maybe....

	-----------------------------------------From: "Rob Tillaart" 
To: "RobTillaart/AD9833"
Cc: "XRAD-XRAY", "Mention"
Sent: Friday November 15 2024 7:25:46AM
Subject: Re: [RobTillaart/AD9833] AD9833 Duty Cycle Control (Issue
#21)

	From - 
[1]https://oshwlab.com/DonWinesK5DW/ad9850-signal-generator-module [2]


	Seems to be a 10KOhm pot 

	 image.png (view on web) [3] 

	—
 Reply to this email directly,  view it on GitHub [4], or  unsubscribe
[5].
 You are receiving this because you were mentioned.Message ID:  

Links:
------
[1] https://oshwlab.com/DonWinesK5DW/ad9850-signal-generator-module
[2] https://oshwlab.com/DonWinesK5DW/ad9850-signal-generator-module
[3]
https://github.com/user-attachments/assets/367b1d6f-eaac-442f-a28a-d2350942db4b
[4]
https://github.com/RobTillaart/AD9833/issues/21#issuecomment-2478703051
[5]

**Comment by XRAD-XRAY** [comment]
and......I do have digital pots as well!! Those are nice with teensy
or arduino....

	-----------------------------------------From: "Rob Tillaart" 
To: "RobTillaart/AD9833"
Cc: "XRAD-XRAY", "Mention"
Sent: Friday November 15 2024 6:17:05AM
Subject: Re: [RobTillaart/AD9833] AD9833 Duty Cycle Control (Issue
#21)

	@XRAD-XRAY [1] 

	How about 

	* 
[2]https://microcontrollerslab.com/interface-ad9850-dds-signal-generator-module-with-arduino-pinout-features/
[3]

	It has a duty cycle potentiometer which in theory could be replaced
by a digital potentiometer. 

	Cannot see the Ohm range of the potentiometer and if it is linear or
logarithmic 

	Library for frequency:  [4]https://github.com/RobTillaart/AD985X [5]
 Also have several digipot libraries. 

	—
 Reply to this email directly,  view it on GitHub [6], or  unsubscribe
[7].
 You are receiving this because you were mentioned.Message ID:  

Links:
------
[1] https://github.com/XRAD-XRAY
[2]
https://microcontrollerslab.com/interface-ad9850-dds-signal-generator-module-with-arduino-pinout-features/
[3]
https://microcontrollerslab.com/interface-ad9850-dds-signal-generator-module-with-arduino-pinout-features/
[4] https://github.com/RobTillaart/AD985X
[5] https://github.com/RobTillaart/AD985X
[6]
https://github.com/RobTillaart/AD9833/issues/21#issuecomment-2478591181
[7]

**Comment by XRAD-XRAY** [comment]
I will look into these! TY!

	-----------------------------------------From: "Rob Tillaart" 
To: "RobTillaart/AD9833"
Cc: "XRAD-XRAY", "Mention"
Sent: Friday November 15 2024 5:25:13AM
Subject: Re: [RobTillaart/AD9833] AD9833 Duty Cycle Control (Issue
#21)

	Found two analog kits for function generators
 Max038 and XR2206
 Might be interesting to do for testing / experiment 

	—
 Reply to this email directly,  view it on GitHub [1], or  unsubscribe
[2].
 You are receiving this because you were mentioned.Message ID:  

Links:
------
[1]
https://github.com/RobTillaart/AD9833/issues/21#issuecomment-2478499576
[2]

**Comment by XRAD-XRAY** [comment]
Yes, I have this schematic. Thank you!
I used a similar method to control gain which worked out really nicely
from 0 to full 6vpp, and it did not mess up the square wave form :)

	-----------------------------------------From: "Rob Tillaart" 
To: "RobTillaart/AD9833"
Cc: "XRAD-XRAY", "Mention"
Sent: Friday November 15 2024 7:28:49AM
Subject: Re: [RobTillaart/AD9833] AD9833 Duty Cycle Control (Issue
#21)

	@XRAD-XRAY [1] 

	Opamp trick 

	 image.png (view on web) [2] 

	—
 Reply to this email directly,  view it on GitHub [3], or  unsubscribe
[4].
 You are receiving this because you were mentioned.Message ID:  

Links:
------
[1] https://github.com/XRAD-XRAY
[2]
https://github.com/user-attachments/assets/081ea2af-5983-46f9-8dcd-23feb42893fd
[3]
https://github.com/RobTillaart/AD9833/issues/21#issuecomment-2478707846
[4]

**Comment by XRAD-XRAY** [comment]
and you may enjoy some of my builds(some use your fantastic
codes!!):Goldenarch3 - YouTube [1]all have links to code and build
details at Adafruit. I have not posted in a bit, but have several new
projects going on!

	-----------------------------------------From: "Rob Tillaart" 
To: "RobTillaart/AD9833"
Cc: "XRAD-XRAY", "Mention"
Sent: Friday November 15 2024 7:28:49AM
Subject: Re: [RobTillaart/AD9833] AD9833 Duty Cycle Control (Issue
#21)

	@XRAD-XRAY [2] 

	Opamp trick 

	 image.png (view on web) [3] 

	—
 Reply to this email directly,  view it on GitHub [4], or  unsubscribe
[5].
 You are receiving this because you were mentioned.Message ID:  

Links:
------
[1] https://www.youtube.com/user/Goldenarch3/videos
[2] https://github.com/XRAD-XRAY
[3]
https://github.com/user-attachments/assets/081ea2af-5983-46f9-8dcd-23feb42893fd
[4]
https://github.com/RobTillaart/AD9833/issues/21#issuecomment-2478707846
[5]

**Comment by RobTillaart** [comment]
> but the issue was the output wave is shark fin and not square

Sounds like an RC effect, adding a transistor (switching a larger current) might solve that.

**Comment by RobTillaart** [comment]
Looked at youtube, 
The lidar is looking 👍

**Comment by XRAD-XRAY** [comment]
Thx! And I will give the resistor a try on the shark fin.

________________________________
