### ISSUE TITLE
investigate AD9834 compatibility

### ISSUE THREAD

**Issue by RobTillaart** [RobTillaart/AD9833#4]
Looks quite similar at first sight

**Comment by KarenColumbo** [comment]
Yeah. At first glance higher max frequency due to higher clock rate. And hardware "sleep" and "reset" pins. Dual outputs. Lotsa pins. ~ 14 Euros p.p. @ Mouser. Only fully staffed sig gen boards, no breakout boards available a.f.a.i.c.s. Would also be quite handy in a DIY synth context.

**Comment by RobTillaart** [comment]
Will not investigate further on short term. 
It is mentioned in the readme as future activity so it does not need to be an (eternally) open issue on GH.
